### ISSUE TITLE
Getting issue to setup on local with mongodb

### ISSUE THREAD

**Issue by amitdivyarawat** [tayloramitverma/Instagram-clone-using-reactjs-node#3]
Hi, I'm trying to setup this code on my local system and unable to setup database, can you please describe about it

**Comment by tayloramitverma** [comment]
Hi, You can register and create database on mongodb atlas. You have to follow few steps like register, creatre project and setup network then create cluster and database.

I have also created my test database on mongodb atlas server. Here is ref link: https://www.mongodb.com/cloud

Thanks

**Comment by amitdivyarawat** [comment]
Hi, Thanks

It's working now
